//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Property {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Property() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Resources.Property", typeof(Property).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дельта от периода сообщения к точному периоду AV-статистики (миллисекунды с точностью до 0.1 сек)..
        /// </summary>
        internal static string AV_PERIOD_SKEW {
            get {
                return ResourceManager.GetString("AV_PERIOD_SKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дельта от времени сообщения к точному времени получения AV-статистики (миллисекунды).
        /// </summary>
        internal static string AV_TIME_SKEW {
            get {
                return ResourceManager.GetString("AV_TIME_SKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсчет случаев фактического отброса медиаданных из-за переполнения буфера конвейера врезультате неконтролируемого наплыва данных.
        /// </summary>
        internal static string BUF_OVERRUNS {
            get {
                return ResourceManager.GetString("BUF_OVERRUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсчет случаев фактической остановки воспроизведения из-за перебоев доставки медиапотока, которые не буфер конвейера не смог нивелировать.
        /// </summary>
        internal static string BUF_UNDERRUNS {
            get {
                return ResourceManager.GetString("BUF_UNDERRUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий выбранный битрейт при адаптивном стриминге (HLS)..
        /// </summary>
        internal static string CUR_BITRAT {
            get {
                return ResourceManager.GetString("CUR_BITRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий уровень сигнала DVB-приемника в процентах.Используется только для устройств, Текущий уровень сигнала DVB-приемника в процентах. Используется только для устройств, оборудованных DVB-ресивером.
        /// </summary>
        internal static string DVB_LEVEL {
            get {
                return ResourceManager.GetString("DVB_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество сбоев вещания TS-потока (CC discontinuity) за интервал.
        /// </summary>
        internal static string LINK_FAULTS {
            get {
                return ResourceManager.GetString("LINK_FAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Factor - значение характеризующее минимально размер буфера (в миллисекундах), необходимый для устранения текущего джиттера (задержки и опережения в доставке пакетов) равный разнице между самыми большими отклонениями времени доставки за учетный интервал. Подробнее см. http://en.wikipedia.org/wiki/Media_Delivery_Index.
        /// </summary>
        internal static string MDI_DF {
            get {
                return ResourceManager.GetString("MDI_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Loss Rate - среднее количество пакетов потерянное в потоке за секунду, по данным PLC..
        /// </summary>
        internal static string MDI_MLR {
            get {
                return ResourceManager.GetString("MDI_MLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество событий переполнения виртуального буфера (overflow). Событие переполнения возникает если медиаданные приходят раньше срока не более чем на 1 секунду. На изображении данные события, как правило, не отражаются..
        /// </summary>
        internal static string OVERFLOW {
            get {
                return ResourceManager.GetString("OVERFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество UDP-пакетов, полученных за интервал времени.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество UDP-датаграмм, восстановленных SmartTUBE PLC. Поле не заполяется если нет PLC потока..
        /// </summary>
        internal static string RESTORED {
            get {
                return ResourceManager.GetString("RESTORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество событий «антипереполнения» (опустошения) виртуального буфера (underflow). Событие «антипереполнения» возникает если медиаданные приходят позже срока на более чем на 1 секунду. На изображении данные события, как правило, не отражаются..
        /// </summary>
        internal static string UNDERFLOW {
            get {
                return ResourceManager.GetString("UNDERFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аптайм приставки (с момента ее включения), секунды.
        /// </summary>
        internal static string UPTIME {
            get {
                return ResourceManager.GetString("UPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ошибок в данных потока.
        /// </summary>
        internal static string VID_DATA_ERRORS {
            get {
                return ResourceManager.GetString("VID_DATA_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ошибочно декодированных кадров из предыдущего значения.
        /// </summary>
        internal static string VID_DECODE_ERRORS {
            get {
                return ResourceManager.GetString("VID_DECODE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество декодированных видеокадров.
        /// </summary>
        internal static string VID_FRAMES {
            get {
                return ResourceManager.GetString("VID_FRAMES", resourceCulture);
            }
        }
    }
}
